import type { Work } from "./domain.ts";

const HOUR = 60 * 60 * 1000;
const MINUTE = 60 * 1000;

function at(now: Date, offsetMs: number): string {
  return new Date(now.getTime() + offsetMs).toISOString();
}

function work(partial: Work): Work {
  return partial;
}

/**
 * Локальный набор для первого среза. Числа и названия вымышленные.
 * Сроки считаются от момента открытия, чтобы просрочка совпадала с правилом «минус 30 минут».
 */
export function createSeedWorks(now: Date): Work[] {
  const orderUrl = (id: number) => `http://orders.local/card/${id}`;
  return [
    work({
      id: 18420,
      expertId: 17,
      type: "excont",
      condition: "signature",
      conditionName: "Подписание",
      expertTerm: at(now, 5 * HOUR),
      orderTerm: at(now, 48 * HOUR),
      goodCount: 2,
      totalWork: 80,
      orderNum: "ЗК-10420",
      orderUrl: orderUrl(18420),
      clientName: "ООО «Промдеталь»",
      description: "Насос центробежный, комплект уплотнений",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "Ждёт подписи руководителя.",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18502,
      expertId: 17,
      type: "liconfirm",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, 8 * HOUR),
      orderTerm: at(now, 72 * HOUR),
      goodCount: 1,
      totalWork: 40,
      orderNum: "ЗК-10502",
      orderUrl: orderUrl(18502),
      clientName: "АО «Балткомплект»",
      description: "Подтверждение ранее выданного заключения",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "",
      isAsk: false,
      isAskSign: true,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18488,
      expertId: 17,
      type: "license",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -48 * HOUR),
      orderTerm: at(now, 10 * 24 * HOUR),
      goodCount: 4,
      totalWork: 120,
      orderNum: "ЗК-10488",
      orderUrl: orderUrl(18488),
      clientName: "ООО «Нева-Инструмент»",
      description: "Комплект измерительного инструмента",
      managerName: "Громов А.С.",
      leaderName: "Седов П.К.",
      isPayment: false,
      comment: "Пакет направлен, ждём ответ.",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: 3,
    }),
    work({
      id: 18455,
      expertId: 17,
      type: "tnved",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -26 * HOUR),
      orderTerm: at(now, 24 * HOUR),
      goodCount: 3,
      totalWork: 90,
      orderNum: "ЗК-10455",
      orderUrl: orderUrl(18455),
      clientName: "ООО «Промдеталь»",
      description: "Плата управления приводом",
      managerName: "Громов А.С.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "Код уточняется по описанию изготовителя.",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18312,
      expertId: 17,
      type: "consultation",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -10 * HOUR),
      orderTerm: at(now, 36 * HOUR),
      goodCount: 1,
      totalWork: 30,
      orderNum: "ЗК-10312",
      orderUrl: orderUrl(18312),
      clientName: "АО «Северный контур»",
      description: "Консультация по комплекту датчиков",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: false,
      comment: "",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: true,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18540,
      expertId: 17,
      type: "military",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -5 * HOUR),
      orderTerm: at(now, 20 * HOUR),
      goodCount: 2,
      totalWork: 60,
      orderNum: "ЗК-10540",
      orderUrl: orderUrl(18540),
      clientName: "ООО «Ладогамаш»",
      description: "Блок питания промышленный",
      managerName: "Громов А.С.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "Запрос у заказчика, срок приостановлен до ответа.",
      isAsk: false,
      isAskSign: false,
      isAskSend: true,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18580,
      expertId: 17,
      type: "excont",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -3 * HOUR),
      orderTerm: at(now, 12 * HOUR),
      goodCount: 6,
      totalWork: 150,
      orderNum: "ЗК-10580",
      orderUrl: orderUrl(18580),
      clientName: "ООО «Нева-Инструмент»",
      description: "Оптический модуль и кабели",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: false,
      comment: "",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18510,
      expertId: 17,
      type: "excont",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, -20 * MINUTE),
      orderTerm: at(now, 30 * HOUR),
      goodCount: 1,
      totalWork: 75,
      orderNum: "ЗК-10510",
      orderUrl: orderUrl(18510),
      clientName: "АО «Балткомплект»",
      description: "Редуктор промышленный",
      managerName: "Громов А.С.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "Запрос на утверждении у руководителя.",
      isAsk: true,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18471,
      expertId: 17,
      type: "alteration",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, 26 * HOUR),
      orderTerm: at(now, 50 * HOUR),
      goodCount: 1,
      totalWork: 45,
      orderNum: "ЗК-10471",
      orderUrl: orderUrl(18471),
      clientName: "ООО «Промдеталь»",
      description: "Изменение заключения по насосу",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: true,
      licConditionId: null,
    }),
    work({
      id: 18402,
      expertId: 17,
      type: "order",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, 48 * HOUR),
      orderTerm: at(now, 96 * HOUR),
      goodCount: 2,
      totalWork: 50,
      orderNum: "ЗК-10402",
      orderUrl: null,
      clientName: "АО «Северный контур»",
      description: "Комплект крепежа по спецификации заказчика",
      managerName: "Громов А.С.",
      leaderName: "Седов П.К.",
      isPayment: false,
      comment: "Ссылка на карточку заказа не передана.",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18390,
      expertId: 17,
      type: "customUnion",
      condition: "agree",
      conditionName: "Утверждение",
      expertTerm: at(now, 20 * HOUR),
      orderTerm: at(now, 40 * HOUR),
      goodCount: 5,
      totalWork: 100,
      orderNum: "ЗК-10390",
      orderUrl: orderUrl(18390),
      clientName: "ООО «Ладогамаш»",
      description: "Клапан регулирующий, партия",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "На утверждении. В плане видна только с флажком «Утверждение».",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18200,
      expertId: 17,
      type: "excont",
      condition: "close",
      conditionName: "Закрыта",
      expertTerm: at(now, -10 * 24 * HOUR),
      orderTerm: at(now, -8 * 24 * HOUR),
      goodCount: 1,
      totalWork: 40,
      orderNum: "ЗК-10200",
      orderUrl: orderUrl(18200),
      clientName: "ООО «Промдеталь»",
      description: "Закрытая работа в план не попадает",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: true,
      comment: "",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
    work({
      id: 18560,
      expertId: 18,
      type: "excont",
      condition: "work",
      conditionName: "В работе",
      expertTerm: at(now, 4 * HOUR),
      orderTerm: at(now, 24 * HOUR),
      goodCount: 1,
      totalWork: 30,
      orderNum: "ЗК-10560",
      orderUrl: orderUrl(18560),
      clientName: "ООО «Чужой эксперт»",
      description: "Работа другого эксперта",
      managerName: "Орлова Н.И.",
      leaderName: "Седов П.К.",
      isPayment: false,
      comment: "",
      isAsk: false,
      isAskSign: false,
      isAskSend: false,
      isStop: false,
      isInt: false,
      licConditionId: null,
    }),
  ];
}
